[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：不支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持
;多国家分组：不支持

;全球直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN

;拦截净化
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

;服务分流
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

;AI服务
ruleset=🤖 AI服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list

;媒体分流
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list

;最终规则
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=☑️ 手动切换`select`.*
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]☑️ 手动切换`[]DIRECT`.*
custom_proxy_group=🤖 AI服务`select`[]🚀 节点选择`[]☑️ 手动切换`[]DIRECT`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🚀 节点选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]☑️ 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]☑️ 手动切换
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]☑️ 手动切换`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true